services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster-12345
    ports:
      - "9092:9092"

  rocketmq-namesrv:
    image: apache/rocketmq:5.1.3
    container_name: rocketmq-namesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876"

  rocketmq-broker:
    image: apache/rocketmq:5.1.3
    container_name: rocketmq-broker
    depends_on:
      - rocketmq-namesrv
    environment:
      - JAVA_OPT_EXT=-Duser.home=/home/rocketmq
    command: >
      sh -c "mkdir -p /home/rocketmq/conf &&
      printf '%s\n' '
        brokerClusterName=DefaultCluster
        brokerName=broker-a
        brokerId=0
        listenPort=10911
        namesrvAddr=rocketmq-namesrv:9876
        deleteWhen=04
        fileReservedTime=48
        brokerRole=ASYNC_MASTER
        flushDiskType=ASYNC_FLUSH
      ' > /home/rocketmq/conf/broker.conf &&
      sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/conf/broker.conf"
    ports:
      - "10911:10911"  # Broker communication
      - "10909:10909"  # Broker HA service

  bet-settlement-service:
    image: bookmaker/bet-settlement-service
    container_name: bet-settlement-service
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_ROCKETMQ_NAME-SERVER=rocketmq-namesrv:9876
    depends_on:
      - kafka
      - rocketmq-namesrv
      - rocketmq-broker
    ports:
      - "8080:8080"
