spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
    h2:
      console:
        enabled: true
    sql:
      init:
        mode: always

  kafka:
    topic: event-outcomes
    consumer:
      group-id: dev_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.bookmaker.model.EventOutcome
        spring.json.trusted.packages: com.bookmaker.model
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: record

rocketmq:
  topic: bet-settlements
  name-server: ${SPRING_ROCKETMQ_NAME-SERVER:rocketmq-namesrv:9876}
  producer:
    group: dev_group

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG