spring:
  kafka:
    consumer:
      group-id: dev_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
          spring.json.value.default.type: com.bookmaker.model.EventOutcome
          spring.json.trusted.packages: com.bookmaker.model
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: record

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    h2:
      console:
        enabled: true
